url: https://brandenlamb.github.io/branden_lamb/

sass:
  sass_dir: _sass
  style: compressed

collections: 
  authors: 
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins: 
  - jekyll-feed
  - jekyll-sitemap 
  - jekyll-seo-tag
